### ISSUE TITLE
Search is completely unstyled

### ISSUE THREAD

**Issue by Leo40Git** [spinfish/midnightcord#2]
![image](https://user-images.githubusercontent.com/7997354/140657037-46c869fa-18c1-4188-8a75-a9878ea82612.png)

**Comment by Leo40Git** [comment]
Here's a snippet to correct this:
```css
.theme-dark .container-2McqkF {
  background: var(--background-tertiary);
}

.theme-dark .option-2KkUJO::after {
  background: linear-gradient(90deg,
    rgba(54,57,63,0) 0,
    var(--background-tertiary));
}

.theme-dark .focused-2FU0YH {
  background-color: var(--background-secondary);
}

.theme-dark .searchAnswer-23w-CH, .theme-dark .searchFilter-2UfsDk {
  background-color: var(--background-secondary);
}
```
